<?php defined('EMLOG_ROOT') or die('本页面禁止直接访问!');
return array(
	1 => "tubiao", 
	"图标" => "tubiao", 
	2 => "zhuanqian", 
	"赚钱" => "zhuanqian", 
	3 => "guanggao", 
	"广告" => "guanggao", 
	4 => "gouwuguanggaolianmeng", 
	"购物广告联盟" => "gouwuguanggaolianmeng", 
	5 => "shixiaoguanggao", 
	"时效广告" => "shixiaoguanggao", 
	6 => "wangluocaigou", 
	"网络采购" => "wangluocaigou", 
	7 => "chenggong", 
	"成功" => "chenggong", 
	8 => "zhishi", 
	"知识" => "zhishi", 
	9 => "jinen", 
	"技能" => "jinen", 
	10 => "lizhi", 
	"励志" => "lizhi", 
	11 => "xiguan", 
	"习惯" => "xiguan", 
	12 => "moban", 
	"模版" => "moban", 
);